// Default product and service data — loaded into localStorage on first run
export const DEFAULT_PRODUCTS = [
  {
    id: 'p1',
    name: 'Luxe Leather Sofa',
    description: 'Premium Italian leather sofa with a solid oak frame. Three-seater with deep cushions and clean modern lines. Available in cognac, black, and ivory.',
    price: 2499,
    category: 'Living Room',
    image: '',
    stock: 5,
    featured: true,
    createdAt: '2024-01-10',
  },
  {
    id: 'p2',
    name: 'Walnut Dining Table',
    description: 'Solid American walnut dining table with hairpin metal legs. Seats 6 comfortably. Natural grain finish, sealed with food-safe oil.',
    price: 1299,
    category: 'Dining Room',
    image: '',
    stock: 8,
    featured: true,
    createdAt: '2024-01-12',
  },
  {
    id: 'p3',
    name: 'Velvet Accent Chair',
    description: 'Curved accent chair upholstered in deep forest-green velvet. Brass-tipped legs and removable cushion.',
    price: 649,
    category: 'Living Room',
    image: '',
    stock: 12,
    featured: true,
    createdAt: '2024-01-15',
  },
  {
    id: 'p4',
    name: 'Platform Bed Frame',
    description: 'Low-profile platform bed in natural ash wood. No box spring needed. Available in Full, Queen, and King sizes.',
    price: 899,
    category: 'Bedroom',
    image: '',
    stock: 6,
    featured: false,
    createdAt: '2024-01-18',
  },
  {
    id: 'p5',
    name: 'Marble Coffee Table',
    description: 'White Carrara marble top with a brushed-gold steel base. Lightweight yet sturdy.',
    price: 749,
    category: 'Living Room',
    image: '',
    stock: 4,
    featured: false,
    createdAt: '2024-01-20',
  },
  {
    id: 'p6',
    name: 'Bookshelf Unit',
    description: 'Floor-to-ceiling modular bookshelf in matte black steel and oak shelves. 5 tiers, adjustable height.',
    price: 499,
    category: 'Office',
    image: '',
    stock: 10,
    featured: false,
    createdAt: '2024-01-22',
  },
];

export const DEFAULT_SERVICES = [
  {
    id: 's1',
    name: 'Interior Design Consultation',
    description: 'A 2-hour one-on-one session with one of our certified interior designers. We\'ll discuss your space, style preferences, and create a mood board tailored to you.',
    price: 199,
    duration: '2 hours',
    image: '',
    featured: true,
    createdAt: '2024-01-10',
  },
  {
    id: 's2',
    name: 'White-Glove Delivery & Assembly',
    description: 'Our professional team will deliver, place, and fully assemble your furniture in any room. Includes removal of all packaging.',
    price: 149,
    duration: 'Half day',
    image: '',
    featured: true,
    createdAt: '2024-01-10',
  },
  {
    id: 's3',
    name: 'Furniture Restoration',
    description: 'Expert restoration for antique or worn pieces. We refinish, re-upholster, and repair. Bring your cherished furniture back to life.',
    price: 299,
    duration: '3-5 days',
    image: '',
    featured: true,
    createdAt: '2024-01-11',
  },
  {
    id: 's4',
    name: 'Custom Furniture Design',
    description: 'Work directly with our master craftsmen to design and build bespoke furniture pieces. Choose every detail — wood type, dimensions, finish, and hardware.',
    price: 499,
    duration: '4-6 weeks',
    image: '',
    featured: false,
    createdAt: '2024-01-12',
  },
];
